STATE_INFO = {
    "alabama": {"abbrv": "AL"},
    "alaska": {"abbrv": "AK"},
    "arizona": {"abbrv": "AZ"},
    "arkansas": {"abbrv": "AR"},
    "california": {"abbrv": "CA"},
    "colorado": {"abbrv": "CO"},
    "connecticut": {"abbrv": "CT"},
    "delaware": {"abbrv": "DE"},
    "florida": {"abbrv": "FL"},
    "georgia": {"abbrv": "GA"},
    "hawaii": {"abbrv": "HI"},
    "idaho": {"abbrv": "ID"},
    "illinois": {"abbrv": "IL"},
    "indiana": {"abbrv": "IN"},
    "iowa": {"abbrv": "IA"},
    "kansas": {"abbrv": "KS"},
    "kentucky": {"abbrv": "KY"},
    "louisiana": {"abbrv": "LA"},
    "maine": {"abbrv": "ME"},
    "maryland": {"abbrv": "MD"},
    "massachusetts": {"abbrv": "MA"},
    "michigan": {"abbrv": "MI"},
    "minnesota": {"abbrv": "MN"},
    "mississippi": {"abbrv": "MS"},
    "missouri": {"abbrv": "MO"},
    "montana": {"abbrv": "MT"},
    "nebraska": {"abbrv": "NE"},
    "nevada": {"abbrv": "NV"},
    "new hampshire": {"abbrv": "NH"},
    "new jersey": {"abbrv": "NJ"},
    "new mexico": {"abbrv": "NM"},
    "new york": {"abbrv": "NY"},
    "north carolina": {"abbrv": "NC"},
    "north dakota": {"abbrv": "ND"},
    "ohio": {"abbrv": "OH"},
    "oklahoma": {"abbrv": "OK"},
    "oregon": {"abbrv": "OR"},
    "pennsylvania": {"abbrv": "PA"},
    "rhode island": {"abbrv": "RI"},
    "south carolina": {"abbrv": "SC"},
    "south dakota": {"abbrv": "SD"},
    "tennessee": {"abbrv": "TN"},
    "texas": {"abbrv": "TX"},
    "utah": {"abbrv": "UT"},
    "vermont": {"abbrv": "VT"},
    "virginia": {"abbrv": "VA"},
    "washington": {"abbrv": "WA"},
    "west virginia": {"abbrv": "WV"},
    "wisconsin": {"abbrv": "WI"},
    "wyoming": {"abbrv": "WY"},
    "district of columbia": {"abbrv": "DC"},
    "american samoa": {"abbrv": "AS"},
    "guam": {"abbrv": "GU"},
    "northern mariana islands": {"abbrv": "MP"},
    "puerto rico": {"abbrv": "PR"},
    "u.s. virgin islands": {"abbrv": "VI"},
}